### ISSUE TITLE
Tensorflow and API Version not specified

### ISSUE THREAD

**Issue by africandave** [douglasrizzo/dodo_detector#12]
In version 0.8 of dodo_detector the link to install the tensorflow object detection API still opens a version of tensorflow that requires python 3.6. However, installing tensorflow using python 3.6 would not work with this version of dodo_detector which uses python 2.7. So which version of tensorflow on the tensorflow object detection API git page would install tensorflow with python 2.7?

Which version of the tensorflow object detection API do I need to install for it to work with dodo_detector Version 0.8? The one in the main branch is for python 3.6.

**Comment by douglasrizzo** [comment]
In versions 0.9 upwards, I updated this repo so that there is compatibility for both:

- TensorFlow 1.13 through 1.15 + Python 2.7 (usable with ROS Melodic Morenia downwards)\
- TensorFlow >=2 + Python 3 (for ROS Noetic Ninjemys upwards)

Version 0.8 had confusing/incompatible dependencies, so I suggest you update it.
