### ISSUE TITLE
Python version conflict 

### ISSUE THREAD

**Issue by echo-yash** [douglasrizzo/dodo_detector#8]
You should make your code revert back to the previous code which runs on python 2. This will fix this issue and make your dodo_detector_ros package not conflicting with python 3 since roe only work in python 2 not in python 3.

**Comment by douglasrizzo** [comment]
Hi there. I'm aware of that, I'll try to provide one version compatible with Python 2.7 + TensorFlow Object Detection API 1 and another version compatible with Python 3 + TensorFlow Object Detection API 2. Once that's done, I'll revisit the other package and make it compatible with this one again.

**Comment by douglasrizzo** [comment]
I've made version 0.8 of this package provide wrappers for both TF1+py27 and TF2+py3. The ROS package has also been modified to use the TF1+py27 wrapper of this package. Unfortunately, I have no way to test the right now, since I'm not working with object detection and ROS lately, but when I get positive feedback, I'll close this issue.

**Comment by douglasrizzo** [comment]
This has since been fixed.

**Comment by africandave** [comment]
In version 0.8 of dodo_detector the link to install the tensorflow object detection API still opens a version of tensorflow that requires python 3.6. However, installing tensorflow using python 3.6 would not work with this version of dodo_detector which uses python 2.7. So which version of tensorflow on the tensorflow object detection API git page would install tensorflow with python 2.7?
